language: node_js
node_js:
- 8.16.0
- 8.16.1
- 8.16.2
- 10.14.0
- 10.14.1
- 10.14.2
- 10.15.0
- 10.15.1
- 10.15.2
- 10.15.3
- 10.16.0
- 10.16.1
- 10.16.2
- 10.16.3
if: branch IN (master, develop)
script:
- npm test
- npm run upload-coverage
before_install:
- openssl aes-256-cbc -K $encrypted_cfeaf5955b9b_key -iv $encrypted_cfeaf5955b9b_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch: develop
      node_js: '10.16.0'
