language: node_js
node_js:
  - "8.16.0"
  - "8.16.1"
  - "8.16.2"

  - "10.14.0"
  - "10.14.1"
  - "10.14.2"

  - "10.15.0"
  - "10.15.1"
  - "10.15.2"
  - "10.15.3"

  - "10.16.0"
  - "10.16.1"
  - "10.16.2"
  - "10.16.3"
if: branch IN (master, develop)
script:
  - npm test
  - npm run upload-coverage
